import { Geist, Geist_Mono } from "next/font/google";
import "./(public)/globals.css";
import InstallAppsContextProvider from "@/context/InstallAppsContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ph-play-store-next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <InstallAppsContextProvider>{children}</InstallAppsContextProvider>
      </body>
    </html>
  );
}
